version: 0.1
dev:
  global:
    parameters:
      region: ap-south-1
  deploy:
    parameters:
      template_file: template.[yaml|yml|json]
      fail_on_empty_changeset: true
      on_failure: ROLLBACK
      max_wait_duration: 60
      stack_name: LeaveManagementService-stack-SKR
      s3_prefix: leave-management-service-sam-deployments-SKR
      s3_bucket: bounce-records-1
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      parameter_overrides:
        UsersTableName=AuthServiceUsersTable-SKR
        UsersGSIName=Role_Based_index
  sync:
    parameters:
      template_file: template.[yaml|yml|json]
      dependency_layer: true
      skip_deploy_sync: true
      stack_name: LeaveManagementService-stack-SKR
      s3_bucket: bounce-records-1
      s3_prefix: leave-management-service-sam-deployments-SKR
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
